name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          
      - name: Check formatting
        run: cargo fmt --all --check

  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
      
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-cache"
          
      - name: cargo build without flags
        run: cargo build
        
      - name: cargo check warnings
        run: RUSTFLAGS="-D warnings" cargo check
   
      - name: Run tests
        run: |
          # Compile tests but don't run them yet
          cargo test --no-run
          # Find the binary with the correct pattern, excluding .d files
          BINARY_PATH=$(find ./target/debug/deps -type f -name 'TEEService-*' ! -name '*.d' -print -quit)

          if [ ! -f "$BINARY_PATH"]; then
            echo "Unit test binary not found"
            exit 1
          fi

          if [ ! -x "$BINARY_PATH"]; then
            echo "Making binary executable"
            chmod +x "$BINARY_PATH"
          fi

          echo "Running binary at $BINARY_PATH"
          sudo "$BINARY_PATH"
